/*!
Functions that create IRIs for the [Friend of a Friend](http://xmlns.com/foaf/spec/) namespace.

*/

namespace! {
    "foaf",
    "http://xmlns.com/foaf/0.1/",
    {
        agent, "Agent",
        person, "Person",
        name, "name",
        title, "title",
        img, "img",
        depiction, "depiction",
        depicts, "depicts",
        family_name, "familyName",
        given_name, "givenName",
        knows, "knows",
        based_near, "based_near",
        age, "age",
        made, "made",
        maker, "maker",
        primary_topic, "primaryTopic",
        primary_topic_of, "primaryTopicOf",
        project, "Project",
        organization, "Organization",
        group, "Group",
        member, "member",
        document, "Document",
        image, "Image",
        nick, "nick",
        mbox, "mbox",
        homepage, "homepage",
        weblog, "weblog",
        openid, "openid",
        jabber_id, "jabberID",
        mbox_sha1sum, "mbox_sha1sum",
        interest, "interest",
        topic_interest, "topic_interest",
        topic, "topic",
        page, "page",
        workplace_homepage, "workplaceHomepage",
        work_info_homepage, "workInfoHomepage",
        school_homepage, "schoolHomepage",
        publications, "publications",
        current_project, "currentProject",
        past_project, "pastProject",
        account, "account",
        online_account, "OnlineAccount",
        account_name, "accountName",
        account_service_homepage, "accountServiceHomepage",
        personal_profile_document, "PersonalProfileDocument",
        tipjar, "tipjar",
        sha1, "sha1",
        thumbnail, "thumbnail",
        logo, "logo"
    }
}
