//!
//! Provides the `Error` type, and the specific `NameParseError` for errors in
//! parsing values to `Name`, `Namespace`, and `LocalName`.
//!

use strum::{EnumIs, EnumTryAs};
use thiserror::Error;
use url::ParseError as UrlError;

///
/// The `Error` type for this crate.
///
#[derive(Debug, Error, EnumIs, EnumTryAs)]
pub enum Error {
    #[error("An error occured trying to parse a name; error: {0}")]
    Name(#[from] NameParseError),

    #[error("An error occured performing standard I/O; error: {0}")]
    Url(#[from] UrlError),
}

///
/// Denotes an error generated by the [`NameParser`]'s `parse_str` method.
///
#[derive(Debug, Error, EnumIs, EnumTryAs)]
pub enum NameParseError {
    #[error("An empty string was passed, this is not a valid name")]
    EmptyString,
    #[error(
        "The parser encountered a character which is not valid according to it's grammar; input: \"{0}\""
    )]
    InvalidCharacter(String),
    #[error("The parser encountered more `':'` separator characters than expected; input: \"{0}\"")]
    TooManySeparators(String),
    #[error(
        "The Namespace string is missing a `':'` separator character at the end; input: \"{0}\""
    )]
    MissingSeparator(String),
}
