[package]
name = "rdftk_iri"
version = "0.2.2"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2021"
description = "This crate provides an implementation of the IRI and URI specifications."
documentation = "https://docs.rs/rdftk_core/"
repository = "https://github.com/johnstonskj/rust-rdftk.git"
license = "MIT"
readme = "README.md"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
url = "2.5.2"
uuid = { version = "1.10", features = ["v4"] }
